[project]
name = "ny-tap-tuition"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "find-quasi-ids",
    "pandas>=2.2.3",
]

[tool.uv.sources]
find-quasi-ids = { path = "find_quasi_ids", editable = true }
